package me.group8.HmsPmsBackend.application.controller.payload

data class UpdatePatientInfoRequest (
        val employeeId: String,
    val patientId: String,
    val govInsuranceNum: Long,
    val firstName: String,
    val lastName: String,
    val telephone: Long,
    val dateOfBirth: String,
    val gender: String,
    val martialStatus: String,
    val extDoctorId: String,
    val patientStreetNum: Int,
    val patientStreetName: String,
    val patientAptNum: Int,
    val patientPostalCode: String,
    val patientCity: String,
    val patientProvince: String,
    val patientCountry: String,
    val nextOfKinFirstName: String,
    val nextOfKinLastName: String,
    val relationship: String,
    val nextOfKinTelephone: Long,
    val nOKStreetNum: Int,
    val nOKStreetName: String,
    val nOKAptNum: Int,
    val nOKPostalCode: String,
    val nOKCity: String,
    val nOKProvince: String,
    val nOKCountry: String,
)