services:
  hmspmsdb:
    container_name: HmsPms_Database
    build: ./postgres-def
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=HmsPms
    healthcheck:
      test: ["CMD-SHELL", "pg_israedy", "-U", "postgres"]
      interval: 5s
      timeout: 60s
      retries: 5
